#cloud-config
apt:
  conf: |
    Unattended-Upgrade {
      Allowed-Origins {
        "${distro_id}:${distro_codename}-updates";
        "${distro_id}:${distro_codename}-backports";
      };
    };
    APT {
      Periodic {
        Download-Upgradeable-Packages "1";
      };
    };
packages:
  - firefox
  - libcanberra-gtk3-module
  - pulseaudio
runcmd:
  - [ systemctl, disable, --now, snapd, snapd.socket ]
timezone: US/Eastern
