#cloud-config
apt:
  conf: |
    Unattended-Upgrade {
      Allowed-Origins {
        "${distro_id}:${distro_codename}-updates";
        "${distro_id}:${distro_codename}-backports";
      };
    };
    APT {
      Periodic {
        Download-Upgradeable-Packages "1";
      };
    };
packages:
  - pulseaudio
runcmd:
  - [ systemctl, disable, --now, snapd, snapd.socket ]
#  - [ snap, install, '--classic', slack ]  # Snap version of Slack wasn't working (Snap unit files were not disabled). LXD does support Snap though. See https://stgraber.org/2016/12/07/running-snaps-in-lxd-containers/
  - [ wget, 'https://dl.google.com/go/go1.12beta2.linux-amd64.tar.gz' ]
  - [ mkdir, -p, /usr/local/go ]
  - [ rm, -f, slack-desktop-3.2.1-amd64.deb ]
  - [ tar, xvzf, go1.12beta2.linux-amd64.tar.gz, -C, /usr/local/go, --strip-components=1 ]
  - [ rm, -f, go1.12beta2.linux-amd64.tar.gz ]
  - [ apt, --yes, install, git, mercurial, yadm, shellinabox ]
timezone: US/Eastern
